name: First Workflow

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Hello desde github actions
              run: echo "Hello!!! from ${{github.workflow}} triggered by the ${{github.event_name}} done by ${{github.actor}}"
            